import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {fieldsOf,sanitized, type Workflow,type Run,type Source,type Field,type Evidence} from './model';
import {z} from 'zod';
export function db(){if(!env.DB)throw new Error('Database unavailable');return env.DB}
export async function owner(){const u=await getChatGPTUser();if(!u)throw new Error('Sign in to use your private workspace');return u.userId}
export async function body(r:Request){const text=await r.text();if(text.length>100000)throw new Error('Request is too large');return JSON.parse(text)}
export function failure(e:unknown){const message=e instanceof Error?e.message:'Request failed';return Response.json({error:message},{status:message.startsWith('Sign in')?401:400})}
const field=z.object({key:z.string().regex(/^[a-zA-Z0-9_.-]+$/).max(180),label:z.string().min(1).max(100),value:z.string().max(2000),type:z.enum(['string','number','boolean']),purpose:z.enum(['must_match','prefer','context','ignore']),exposure:z.enum(['send','redact','local_only']),include:z.boolean(),maxAge:z.number().int().min(0).max(31536000),sourceId:z.string(),observedAt:z.string().datetime()});
const evidence=z.object({url:z.string().url().max(1000),status:z.number(),requestId:z.string().nullable(),observedAt:z.string().datetime()});
export const workflowSchema=z.object({id:z.string().uuid(),revisionId:z.string().uuid().optional(),version:z.number().int().min(0),name:z.string().trim().min(1).max(100),intent:z.string().trim().min(1).max(1000),verifier:z.string().trim().min(1).max(1000),sources:z.array(z.object({id:z.string().min(1).max(80),kind:z.enum(['github','sample']),transport:z.enum(['server','browser']).optional(),name:z.string().max(180),observedAt:z.string().datetime(),fields:z.array(field).min(1).max(50),evidence:z.array(evidence).max(10)})).min(1).max(8),captureAt:z.enum(['task_complete','after_tool','explicit']),injectAt:z.enum(['before_task','before_tool','on_request']),budget:z.number().int().min(500).max(16000)});
export function validate(raw:unknown){const w=workflowSchema.parse(raw);const fs=fieldsOf(w);if(new Set(fs.map(f=>f.key)).size!==fs.length)throw new Error('Every field needs a unique key');if(!fs.some(f=>f.purpose==='must_match'))throw new Error('Choose at least one Must match field to define the workflow boundary');for(const f of fs){if(f.exposure!=='send'&&['must_match','prefer'].includes(f.purpose))throw new Error(f.label+': private values cannot be used for server matching');if(f.purpose==='must_match'&&!f.value)throw new Error(f.label+' needs a value');}return sanitized(w)}
export async function latest(user:string,id:string):Promise<Workflow>{const row=await db().prepare('SELECT data FROM workflow_revisions WHERE owner=? AND workflow_id=? ORDER BY version DESC LIMIT 1').bind(user,id).first<{data:string}>();if(!row)throw new Error('Save this workflow first');return JSON.parse(row.data)}
export async function listRuns(user:string,id:string):Promise<Run[]>{const rows=await db().prepare('SELECT data FROM observed_runs WHERE owner=? AND workflow_id=? ORDER BY created_at DESC LIMIT 100').bind(user,id).all<{data:string}>();return rows.results.map(r=>JSON.parse(r.data))}
export {github} from './github';
