'use client';

import {useEffect, useRef, useState} from 'react';
import {ArrowDown, ArrowRight, ArrowUpRight, Braces, Check, ChevronLeft, ChevronRight, Circle, Code2, Copy, Download, ExternalLink, FileCode2, Fingerprint, GitBranch, Globe2, Layers3, Loader2, Maximize2, Pause, Play, RotateCcw, Search, ShieldCheck, Terminal, Upload, X} from 'lucide-react';
import {comparison, parseConnection, setupPrompt, sourceRoot, type BrowserRecording, type Connection, type Recording} from '@/lib/connect/data';
import './connect.css';

type View = 'demo'|'connect'|'decisions';
type Agent = 'browser'|'devin'|'dimensional';
const agents: {id: Agent; name: string; category: string; status: string; icon: typeof Code2}[] = [
  {id:'browser',name:'Browser Use',category:'Work on the web',status:'Recorded · memory round trip',icon:Globe2},
  {id:'devin',name:'Devin',category:'Build in a codebase',status:'Recorded · 18 paired runs',icon:Code2},
  {id:'dimensional',name:'Dimensional',category:'Act in physical space',status:'Recorded · MCP agent round trip',icon:Layers3},
];
const fmt = (n: number, digits=0) => n.toLocaleString('en-US',{maximumFractionDigits:digits});
const phases = ['Capture','Store','Recall','Deliver','Verify'];
function Tag({children,tone='quiet'}:{children:React.ReactNode;tone?:string}){return <span className={'mc-tag '+tone}>{children}</span>}
function Metric({label,value,note}:{label:string;value:React.ReactNode;note?:string}){return <div className="mc-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}

export default function Connect({embedded=false,initialAgent='browser',initialView='demo'}:{embedded?:boolean;initialAgent?:Agent;initialView?:View}={}){
  const [view,setView]=useState<View>(initialView),[agent,setAgent]=useState<Agent>(initialAgent);
  const [recording,setRecording]=useState<Recording|null>(null),[browser,setBrowser]=useState<BrowserRecording|null>(null),[dimos,setDimos]=useState<{runs:{case:string;token_usage:{total_tokens:number};captured_calls:number;context_chars:number;verified:boolean;context_delivered_to_model:boolean}[]}|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [task,setTask]=useState('all'),[phase,setPhase]=useState(0),[playing,setPlaying]=useState(false),[present,setPresent]=useState(false);
  const [repo,setRepo]=useState(''),[target,setTarget]=useState('application'),[goal,setGoal]=useState('');
  const [connection,setConnection]=useState<Connection|null>(null),[repoInfo,setRepoInfo]=useState<{name:string;commit:string;language:string}|null>(null),[reading,setReading]=useState(false);
  const [decision,setDecision]=useState('match'),[monthly,setMonthly]=useState(1000);
  const input=useRef<HTMLInputElement>(null);
  const prompt=setupPrompt(target,repo)+(goal.trim()?`\n\nWorkflow requirement: ${goal.trim()}`:'');
  const stats=recording?comparison(recording,task):null;

  async function load(){setLoading(true);setError('');try{
    const [a,b,c]=await Promise.all([fetch('/evidence/devin-recorded.json'),fetch('/evidence/browser-use-recorded.json'),fetch('/evidence/dimensional-recorded.json')]);
    if(!a.ok||!b.ok)throw new Error('The recorded evidence could not be loaded.');
    const br=await b.json() as BrowserRecording;if(!br.complete||!Array.isArray(br.runs)||br.runs.length<2||br.runs.some((r:BrowserRecording['runs'][number])=>!r.receipt?.embedding||!Array.isArray(r.recall_ids))||!br.hard_filter_checks)throw new Error('Browser evidence is incomplete.');setRecording(await a.json());setBrowser(br);if(c.ok)setDimos(await c.json());
  }catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  useEffect(()=>{if(!playing)return;const id=setInterval(()=>setPhase(p=>{if(p>=4){setPlaying(false);return p}return p+1}),2200);return()=>clearInterval(id)},[playing]);
  useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id)},[notice]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setPresent(false);if(present&&e.key==='ArrowRight')setPhase(p=>Math.min(4,p+1));if(present&&e.key==='ArrowLeft')setPhase(p=>Math.max(0,p-1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[present]);

  async function copy(value:string){try{await navigator.clipboard.writeText(value);setNotice('Copied to clipboard.')}catch{setError('Clipboard unavailable. Select the text and copy it.')}}
  function download(name:string,value:string){const url=URL.createObjectURL(new Blob([value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function importReport(file?:File){if(!file)return;setError('');try{if(file.size>1_000_000)throw new Error('Choose a connection report smaller than 1 MB.');const parsed=parseConnection(await file.text());setConnection(parsed);setView('connect');setNotice('Local report opened. Nothing was uploaded.')}catch(e){setError((e as Error).message)}finally{if(input.current)input.current.value=''}}
  async function inspectRepo(){setReading(true);setError('');setRepoInfo(null);try{const r=await fetch('/api/source',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repo})});const d=await r.json() as {error?:string;name:string;fields:{key:string;value:string}[]};if(!r.ok)throw new Error(d.error||'Repository could not be read.');const field=(key:string)=>d.fields.find(f=>f.key===key)?.value||'Unknown';setRepoInfo({name:d.name,commit:field('github.commit'),language:field('github.language')})}catch(e){setError((e as Error).message)}finally{setReading(false)}}
  function choose(id:Agent){setAgent(id);setPlaying(false);setPhase(0);setTask('all')}

  return <div className={'mc-shell '+(present?'mc-present':'')}>
    <header className="mc-top" data-embedded={embedded}><a href="/" className="mc-brand">memorable<span>*</span><b>CONNECT</b></a><nav aria-label="Main navigation">
      {([['demo','Demo room'],['connect','Connect an agent'],['decisions','Memory decisions']] as [View,string][]).filter(([id])=>!embedded||initialAgent==='browser'||id!=='decisions').map(([id,label])=><button key={id} aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>{setView(id);setPlaying(false)}}>{label}</button>)}
    </nav><a className="mc-workflows" href="/workflows">Workflow Studio <ArrowUpRight size={14}/></a></header>
    <input ref={input} type="file" accept="application/json,.json" aria-label="Import connection report" className="mc-file" onChange={e=>void importReport(e.target.files?.[0])}/>
    {notice&&<div className="mc-toast" role="status"><Check size={16}/>{notice}</div>}
    {error&&<div className="mc-error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
    <main className="mc-main">
      <div className="mc-heading"><div><span className="mc-eyebrow">{view==='connect'?'01 / CONNECT':view==='demo'?'02 / WATCH IT WORK':'03 / UNDERSTAND THE RECALL'}</span>
        <h1>{view==='connect'?'Connect a repository':view==='demo'?'Run comparison':'Recall decisions'}</h1>
        <p>{view==='connect'?'Start in your repo. Define what matters. Verify a real round trip.':view==='demo'?'Explore recorded runs, inspect the evidence, and compare what changed.':'Follow a stored workflow through the boundaries you defined.'}</p></div>
        <button className="mc-button secondary mc-presentation-button" onClick={()=>setPresent(p=>!p)}>{present?<X size={16}/>:<Maximize2 size={16}/>} {present?'Exit presentation':'Present'}</button>
      </div>

      {view==='demo'&&<>
        {agent!=='devin'&&<a className="mc-replay-link" href={'/?environment=replay&agent='+agent}><Play size={16}/>Watch the recorded {agent==='browser'?'browser run':'robot trace'}<span>Screens + tool calls + memory events →</span></a>}
        {!embedded&&<div className="mc-agent-grid" role="group" aria-label="Agent use cases">{agents.map(a=><button key={a.id} className={'mc-agent-card '+(agent===a.id?'selected':'')} onClick={()=>choose(a.id)} aria-pressed={agent===a.id}><a.icon size={23}/><span><strong>{a.name}</strong><small>{a.category}</small></span><ArrowUpRight size={16}/><div><span className={'mc-dot '+(a.id==='dimensional'?'amber':'')}/>{a.status}</div></button>)}</div>}
        {loading?<div className="mc-loading"><Loader2 className="spin"/>Loading recorded evidence…</div>:!browser||!recording?<div className="mc-panel mc-empty"><h2>Evidence is unavailable</h2><button className="mc-button" onClick={()=>void load()}>Try again</button></div>:agent==='browser'?<>
          <section className="mc-demo-panel"><div className="mc-section-top"><div><Tag tone="mint">Recorded agent execution</Tag><h2>Find the next page. Keep the procedure.</h2><p>Two fresh Browser Use agents on quotes.toscrape.com · September 19, 2026</p></div><a className="mc-text-link" href="/evidence/browser-use-recorded.json" target="_blank" rel="noreferrer">View source evidence <ExternalLink size={14}/></a></div>
            <div className="mc-lanes">{browser.runs.map((r,i)=><article className={'mc-lane '+(i?'with-memory':'')} key={r.id}><div className="mc-lane-title"><span>0{i+1}</span><h3>{i?'With previous experience':'First encounter'}</h3><Tag>{i?'Recall delivered':'Empty memory'}</Tag></div>
              <div className="mc-task"><span>TASK</span><p>{i?'Move to the next quote-listing page and check ten entries.':'Visit page two and confirm ten quotes.'}</p></div>
              <div className="mc-action-path">{r.agent_actions.map((a,j)=><span key={a}>{j>0&&<ArrowRight size={13}/>}<code>{a}</code></span>)}</div>
              <div className="mc-lane-metrics"><Metric label="Model steps" value={r.model_steps}/><Metric label="Captured actions" value={r.captured_actions}/><Metric label="Recalled references" value={r.recall_ids.length}/></div>
              <div className="mc-outcome"><Check size={16}/><div><strong>Page two · 10 quote cards</strong><small>Checked independently against the browser DOM</small></div></div>
              <div className="mc-lane-foot">{i?`${r.context_bytes} bytes of recalled reference reached model messages`:'Procedure stored locally with a production embedding'}</div>
            </article>)}</div>
            <div className="mc-finding"><Fingerprint size={19}/><p><strong>Memory transferred successfully.</strong> Both runs took three steps. This example establishes the round trip; a speedup was not demonstrated.</p></div>
          </section>
          <section className="mc-walkthrough"><div className="mc-section-top"><div><span className="mc-eyebrow">EVIDENCE WALKTHROUGH</span><h2>Follow the handoff.</h2></div><button className="mc-button secondary" onClick={()=>{if(phase===4)setPhase(0);setPlaying(p=>!p)}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play walkthrough'}</button></div>
            <div className="mc-phase-rail">{phases.map((p,i)=><button key={p} className={phase===i?'current':phase>i?'visited':''} onClick={()=>{setPhase(i);setPlaying(false)}}><span>{phase>i?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{p}</button>)}</div>
            <div className="mc-phase-content" aria-live="polite"><span className="mc-phase-number">0{phase+1}</span><div><h3>{['Capture actions and actual outcomes','Store the accepted trace','Find it with a different phrasing','Deliver bounded reference context','Check the result in the browser'][phase]}</h3><p>{[
              'Three action records were captured. The extract action kept an unknown marker instead of inventing a successful mapping.',
              'The existing encrypted local store returned a receipt. The configured service produced a BGE-M3 embedding with 1,024 dimensions.',
              'A fresh process retrieved the first run by a paraphrased request. Project, website and verified-outcome filters were checked first.',
              'The second agent received 500 bytes of historical reference. The reference was observed in its actual model-message list.',
              'The final URL and ten quote cards were checked directly. This verifies the browser outcome, independently of the agent’s final answer.'
            ][phase]}</p></div><Tag>{phase===3?'Context observed':phase===4?'Outcome verified':'Recorded evidence'}</Tag></div>
            <small className="mc-muted">Playback advances through documented evidence. It does not launch a browser agent.</small>
          </section>
        </>:agent==='devin'&&stats?<>
          <section className="mc-demo-panel"><div className="mc-section-top"><div><Tag tone="mint">Recorded benchmark</Tag><h2>A coding teammate with a previous run to consult.</h2><p>Devin · Sonnet · September 19, 2026 · {stats.pairs.length} matched pairs</p></div><label className="mc-select-label">TASK GROUP<select value={task} onChange={e=>setTask(e.target.value)}><option value="all">All nine tasks</option>{[...new Set(recording.runs.map(r=>r.task))].map(t=><option key={t} value={t}>{t}</option>)}</select></label></div>
            <div className="mc-lanes">{(['cold','warm'] as const).map((side,i)=><article className={'mc-lane '+(i?'with-memory':'')} key={side}><div className="mc-lane-title"><span>0{i+1}</span><h3>{i?'With recalled procedure':'Without memory'}</h3></div><div className="mc-lane-metrics"><Metric label="Mean run time" value={<>{fmt(stats.mean(side,'duration_s'),1)}<em>s</em></>}/><Metric label="Mean context tokens" value={fmt(stats.mean(side,'context_tokens'))}/></div><div className="mc-bar" style={{'--bar':`${stats.mean(side,'context_tokens')/Math.max(stats.mean('cold','context_tokens'),stats.mean('warm','context_tokens'))*100}%`} as React.CSSProperties}><i/></div><div className="mc-small-metrics"><span>{fmt(stats.mean(side,'tool_calls'),1)} tool calls</span><span>{fmt(stats.mean(side,'discovery_calls'),1)} discovery calls</span><span>{stats.passed(side)}/{stats.pairs.length} reported checks passed</span></div></article>)}</div>
            <div className="mc-deltas">{(['duration_s','context_tokens','discovery_calls'] as const).map((k,i)=>{const d=stats.delta(k);return <div key={k} className={d!==null&&d<0?'regression':''}>{d!==null&&d>=0?<ArrowDown size={16}/>:<ArrowUpRight size={16}/>}<strong>{d===null?'—':fmt(Math.abs(d),1)+'%'}</strong><span>{['run time','context tokens','discovery calls'][i]} {d!==null&&d<0?'increase':'reduction'}</span></div>})}</div>
            <div className="env-doc-control"><strong>Static-document control:</strong> {fmt(stats.docMean('context_tokens'))} mean context tokens and {fmt(stats.docMean('duration_s'),1)}s per run. Recalled procedures used {fmt(stats.mean('warm','context_tokens'))} tokens and {fmt(stats.mean('warm','duration_s'),1)}s. {task==='all'?'Static documentation performed similarly across this dataset.':'Control results vary by task; compare all three approaches.'}</div><div className="mc-finding"><ShieldCheck size={20}/><p>These measurements use <strong>legacy local Headstart retrieval</strong>, not the new metadata SDK. Context tokens include cached input and are not billable-cost savings. Provider charges and memory overhead were not recorded.</p></div>
          </section>
          <div className="mc-bottom-grid"><section className="mc-panel"><div className="mc-section-top"><h2>Every pair, including regressions</h2><a className="mc-text-link" href="/evidence/devin-recorded.json" target="_blank" rel="noreferrer">Source JSON <ExternalLink size={14}/></a></div><div className="mc-table-scroll"><table className="mc-pair-table"><thead><tr><th>Task / repeat</th><th>Time, s</th><th>Context tokens</th><th>Result</th></tr></thead><tbody>{stats.pairs.map(({cold,warm})=><tr key={cold.task+cold.repeat}><td>{cold.task} <small>/{cold.repeat}</small></td><td>{cold.duration_s} → {warm.duration_s}</td><td>{fmt(cold.context_tokens)} → {fmt(warm.context_tokens)}</td><td>{cold.pass&&warm.pass?'Both passed':'Check failure'}</td></tr>)}</tbody></table></div><p className="mc-muted">Recorded result summaries; raw native-agent exports are not included. No fresh Devin execution occurred on this machine.</p></section>
            <section className="mc-panel mc-impact"><span className="mc-eyebrow">OPERATIONAL EFFICIENCY</span><h2>What could this mean at your scale?</h2><label>Similar runs per month<input type="number" min="1" max="1000000" value={monthly} onChange={e=>setMonthly(Math.min(1_000_000,Math.max(1,Number(e.target.value)||1)))}/></label><strong>{fmt((stats.mean('cold','duration_s')-stats.mean('warm','duration_s'))*monthly/3600,1)} <span>agent-hours</span></strong><p>Projected difference at the selected workload. This is a linear estimate, not measured monthly savings or human labor saved.</p><div className="mc-cost"><span>Dollar savings</span><b>Not measured</b></div><small>Formula: mean seconds per run difference × runs ÷ 3,600. Includes no hosting or memory-service costs.</small></section></div>
        </>:<section className="mc-panel"><div className="mc-section-top"><div><Tag tone="mint">Recorded external agent · real MCP</Tag><h2>Carry experience across dimOS agent sessions.</h2><p>GPT-4.1-mini called the upstream dimOS coordinator · September 20, 2026</p></div><a className="mc-text-link" href="/evidence/dimensional-recorded.json" target="_blank" rel="noreferrer">Source evidence <ExternalLink size={14}/></a></div>{dimos?<><table className="env-dimos-table"><thead><tr><th>Run</th><th>MCP calls</th><th>Model tokens</th><th>Recalled context</th><th>Readiness</th></tr></thead><tbody>{dimos.runs.map(r=><tr key={r.case}><td>{r.case==='first'?'First mission':'Fresh agent + recall'}</td><td>{r.captured_calls}</td><td>{r.token_usage.total_tokens}</td><td>{r.context_chars} characters{r.context_delivered_to_model?' · in model input':''}</td><td>{r.verified?'Verified':'Not verified'}</td></tr>)}</tbody></table><div className="mc-finding"><Fingerprint size={19}/><p>The second agent received the first mission’s procedure and called the real <code>server_status</code> and <code>list_modules</code> tools. Storage and lexical recall ran locally; embeddings were disabled. Tokens increased from 435 to 552. This verifies memory transfer for robotics tools, not a performance gain.</p></div><div className="env-doc-control"><strong>Execution scope:</strong> server readiness only. This recording contains no robot movement. The adapter wraps an external MCP agent; it does not intercept dimOS’s built-in agent automatically.</div></>:<div className="mc-empty">Dimensional evidence could not be loaded.</div>}</section>}

      </>}

      {view==='connect'&&<div className="mc-connect-grid"><section className="mc-panel mc-setup"><span className="mc-eyebrow">START WHERE YOU BUILD</span><h2>Which agent should remember?</h2><div className="mc-targets">{[['application','The agent in my app','Wire memory into its task lifecycle.'],['coding-agent','My coding assistant','Configure hooks for this repository.']].map(([id,label,desc])=><button key={id} className={target===id?'selected':''} onClick={()=>setTarget(id)} aria-pressed={target===id}><span className="mc-radio">{target===id&&<i/>}</span><span><strong>{label}</strong><small>{desc}</small></span></button>)}</div>
        <label className="mc-label" htmlFor="repo">Repository <span>optional · public GitHub</span></label><div className="mc-input-row"><GitBranch size={17}/><input id="repo" value={repo} onChange={e=>{setRepo(e.target.value);setRepoInfo(null)}} placeholder="owner/repository"/><button aria-label="Read repository" disabled={reading||!repo.trim()} onClick={()=>void inspectRepo()}>{reading?<Loader2 className="spin" size={17}/>:<Search size={17}/>}</button></div>
        {repoInfo&&<div className="mc-repo-read"><Check size={15}/><div><strong>{repoInfo.name}</strong><span>{repoInfo.language} · {repoInfo.commit.slice(0,8)}</span><small>Repository read. Runtime integration has not been performed.</small></div></div>}
        <label className="mc-label" htmlFor="goal">What should it remember? <span>optional</span></label><textarea id="goal" value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Successful inspection routines, scoped to the site and map version…" rows={3}/>
        <div className="mc-setup-actions"><button className="mc-button" onClick={()=>void copy(prompt)}><Copy size={16}/>Copy prompt for your agent <ArrowRight size={16}/></button><button className="mc-text-link" onClick={()=>download('memorable-connect-prompt.md',prompt)}>Download instructions</button></div><p className="mc-muted">Paste into the coding agent already open in your repo. It can inspect the code, propose the changes, and execute your real workflow.</p>
        <details className="mc-details"><summary>Read the full integration prompt</summary><pre>{prompt}</pre></details>
      </section><div className="mc-stack"><section className="mc-terminal"><div><span className="mc-terminal-dots">● ● ●</span><span>IN YOUR REPOSITORY</span><button aria-label="Copy setup commands" onClick={()=>void copy('node /path/to/environment-mem/bin/headstart connect --target '+target+' --json')}><Copy size={14}/></button></div><pre><span>$ </span>headstart connect --target {target}{'\n'}<span>  </span># Inspect source and report candidate hooks{'\n'}<span>  </span># No code changes or execution from this command{'\n'}<span>  </span># Give the report to your coding agent to integrate</pre><footer>Development branch · requires a compatible CLI build</footer></section>
        <section className="mc-panel mc-import"><div className="mc-icon-square"><Upload size={23}/></div><h2>Inspect your local connection</h2><p>Run <code>connect --json</code> in the checkout, save its output, then open the report here.</p><button className="mc-button secondary" onClick={()=>input.current?.click()}><Upload size={16}/>Open connection report</button><small>The report stays in this tab. No repository files or credentials are uploaded.</small></section>
        <a className="mc-source-card" href={sourceRoot+'/tree/main'} target="_blank" rel="noreferrer"><FileCode2 size={22}/><div><strong>One SDK. Optional adapters.</strong><span>Inspect the code and version requirements</span></div><ArrowUpRight size={18}/></a>
      </div>
      {connection&&<section className="mc-panel mc-connection-report"><div className="mc-section-top"><div><Tag>Imported CLI report</Tag><h2>{connection.repo.name}</h2><p>{connection.target||'Target not selected'} · {connection.frameworks.map(f=>f.label).join(', ')||'Custom runtime'}</p></div><button className="mc-text-link" onClick={()=>setConnection(null)}>Close report <X size={14}/></button></div><div className="mc-report-stages">{Object.entries(connection.status).map(([k,v])=><div key={k}>{v?<Check size={16}/>:<Circle size={16}/>}<span>{k==='contextDelivered'?'Context delivered':k}</span><small>{v?'Reported by CLI':'Not observed'}</small></div>)}</div><div className="mc-seams">{connection.seams.map((s,i)=><div key={i}><Tag>{s.kind}</Tag><code>{s.file||'No source found'}{s.line?':'+s.line:''}</code><span>{s.status.replaceAll('_',' ')}</span><p>{s.detail}</p></div>)}</div><details className="mc-details"><summary>Metadata roles and remaining work</summary><pre>{JSON.stringify(connection.metadata,null,2)}</pre>{connection.limitations.map((l,i)=><p key={i}>{l}</p>)}{connection.nextSteps.map((l,i)=><p key={i}>{l}</p>)}</details></section>}
      </div>}

      {view==='decisions'&&(loading?<div className="mc-loading">Loading recorded receipts…</div>:!browser?<div className="mc-empty">Recall evidence is unavailable. <button className="mc-button" onClick={()=>void load()}>Retry</button></div>:<>
        <section className="mc-decision-top"><div><Tag tone="mint">Browser Use · recorded controls</Tag><h2>Relevant is not the same as eligible.</h2><p>One stored procedure. Four ways to ask for it. These outcomes come from the recorded metadata checks.</p></div><div className="mc-decision-switch" role="group" aria-label="Recall scenario">{[['match','Matching task'],['project','Different project'],['website','Different website'],['outcome','Unverified outcome']].map(([id,label])=><button key={id} className={decision===id?'active':''} onClick={()=>setDecision(id)} aria-pressed={decision===id}>{label}</button>)}</div></section>
        <div className="mc-decision-grid"><section className="mc-panel"><span className="mc-eyebrow">DEVELOPER DEFINITION</span><h2>Choose the meaning once.</h2><div className="mc-role-list">{[['project','filter','Keep workflows in the same project.'],['website','filter','Require the same website.'],['outcome','filter','Only retrieve verified runs.'],['task · workflow · steps','semantic','Find a similar procedure by meaning.'],['verification','context','Return the evidence with the match.'],['runNotes','private','Exclude from embeddings and recall.']].map(([field,role,desc])=><div key={field}><code>{field}</code><Tag tone={role==='semantic'?'mint':'quiet'}>{role}</Tag><p>{desc}</p></div>)}</div><small className="mc-muted">Private metadata is still stored locally. It does not mean “never stored.”</small></section>
          <section className="mc-panel"><span className="mc-eyebrow">RECORDED RESULT</span><div className={'mc-decision-result '+(decision==='match'?'':'blocked')}><ShieldCheck size={26}/><h2>{decision==='match'?'Applicable workflow found':'Excluded before ranking'}</h2><p>{decision==='match'?'The paraphrased request retrieved the first run and delivered its reference.':`The ${decision} constraint excluded the saved workflow. No query embedding was requested.`}</p></div><div className="mc-lane-metrics"><Metric label="Eligible records" value={decision==='match'?1:browser?.hard_filter_checks[decision]?.eligible??'—'}/><Metric label="Matches" value={decision==='match'?browser.runs[1].recall_ids.length:browser.hard_filter_checks[decision]?.matches??'—'}/><Metric label="Context bytes" value={decision==='match'?browser?.runs[1]?.context_bytes??'—':0}/></div><div className="mc-receipt"><span>MEMORY ID</span><code>{decision==='match'?browser?.runs[0]?.id||'Loading…':'No memory selected'}</code><span>EMBEDDING</span><code>{decision==='match'?browser.runs[0].receipt.embedding.model+' · '+browser.runs[0].receipt.embedding.dimensions+' dimensions':'Not needed'}</code><span>STORAGE</span><code>Existing local procedure store</code></div><a className="mc-text-link" href="/evidence/browser-use-recorded.json" target="_blank" rel="noreferrer">Inspect the underlying receipt <ExternalLink size={14}/></a></section>
        </div><p className="mc-muted mc-bottom-note">These controls replay recorded evidence. This page does not call the retrieval service. Fields shown as filters are application constraints, not authentication boundaries.</p>
      </>)}
      <footer className="mc-footer"><span>memorable<span>*</span> <i>Experience for your next run.</i></span><div><a href={sourceRoot} target="_blank" rel="noreferrer">Source <ArrowUpRight size={13}/></a><a href="https://www.memorable.sh/docs" target="_blank" rel="noreferrer">Documentation <ArrowUpRight size={13}/></a><span>Recorded evidence · no live agent connected</span></div></footer>
    </main>
  </div>;
}
