'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronLeft,ChevronRight,Code2,Database,ExternalLink,Eye,Globe2,Layers3,Maximize2,Pause,Play,RotateCcw,ShieldCheck,Sparkles,Terminal,X} from 'lucide-react';
import {parseReplay,type ReplayRecording} from '@/lib/connect/replay';
import './replay.css';
const kinds={start:{label:'Task started',icon:Terminal},tool:{label:'Recorded tool event',icon:Code2},store:{label:'Store',icon:Database},recall:{label:'Recall',icon:Sparkles},inject:{label:'Context delivered',icon:ArrowRight},verify:{label:'Independent check',icon:ShieldCheck}};
const demos=[{id:'browser',label:'Browser Use',icon:Globe2,description:'Learn a web task → reuse the procedure'},{id:'dimensional',label:'Dimensional',icon:Layers3,description:'Robot camera → measured arrival check'}];
export default function Replay({onMeasurements}:{onMeasurements:(id:string)=>void}){
 const [agent,setAgent]=useState('browser'),[recording,setRecording]=useState<ReplayRecording|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 const [cursor,setCursor]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[present,setPresent]=useState(false),[imageError,setImageError]=useState('');
 const activeRow=useRef<HTMLButtonElement>(null),playerRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!present||!playerRef.current)return;const root=playerRef.current,previous=document.activeElement;const siblings:{element:HTMLElement;inert:boolean}[]=[];let branch:HTMLElement=root;while(branch.parentElement){for(const sibling of branch.parentElement.children){if(sibling instanceof HTMLElement&&sibling!==branch){siblings.push({element:sibling,inert:sibling.inert});sibling.inert=true}}branch=branch.parentElement}root.querySelector<HTMLButtonElement>('button')?.focus();return()=>{for(const s of siblings)s.element.inert=s.inert;if(previous instanceof HTMLElement&&previous.isConnected)previous.focus()}},[present]);
 useEffect(()=>{const a=new URLSearchParams(location.search).get('agent');if(demos.some(d=>d.id===a))setAgent(a!)},[]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setImageError('');setRecording(null);setCursor(0);setPlaying(false);fetch('/evidence/replays/'+agent+'/replay.json',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('The recording could not be loaded.');return parseReplay(await r.json(),agent)}).then(setRecording).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[agent,retry]);
 const events=recording?.chapters.flatMap((chapter,chapterIndex)=>chapter.events.map(event=>({...event,chapter,chapterIndex})))||[];
 const current=events[cursor],total=events.length,ended=total>0&&cursor===total-1;
 // Steps have a presentation cadence. These intervals are never reported as agent timings.
 useEffect(()=>{if(!playing||!total)return;const timer=setTimeout(()=>{if(cursor>=total-1)setPlaying(false);else setCursor(c=>c+1)},2800/speed);return()=>clearTimeout(timer)},[playing,cursor,total,speed]);
 useEffect(()=>{const row=activeRow.current;const parent=row?.parentElement;if(row&&parent){if(parent.scrollHeight>parent.clientHeight)parent.scrollTo({top:Math.max(0,row.offsetTop-parent.clientHeight/2+row.clientHeight/2),behavior:'instant'});if(parent.scrollWidth>parent.clientWidth)parent.scrollTo({left:Math.max(0,row.offsetLeft-parent.clientWidth/2+row.clientWidth/2),behavior:'instant'})}},[cursor]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const root=playerRef.current;if(!(e.target instanceof HTMLElement)||!root?.contains(e.target)||e.target.closest('[role=dialog]')&&e.target.closest('[role=dialog]')!==root)return;if(present&&e.key==='Tab'){const nodes=root.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,a[href],summary');const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}if(/INPUT|TEXTAREA|SELECT/.test((e.target as HTMLElement)?.tagName)||!(e.target instanceof HTMLElement)||e.target.isContentEditable)return;if(e.key==='Escape')setPresent(false);if(!total)return;if(e.key==='ArrowRight'){e.preventDefault();setPlaying(false);setCursor(c=>Math.min(total-1,c+1))}if(e.key==='ArrowLeft'){e.preventDefault();setPlaying(false);setCursor(c=>Math.max(0,c-1))}if(e.code==='Space'&&e.target.tagName!=='BUTTON'&&total){e.preventDefault();if(ended)setCursor(0);setPlaying(p=>!p)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[total,ended,present]);
 const seen=events.slice(0,cursor+1).filter(e=>e.chapterIndex===current?.chapterIndex);
 const observedScreenshot=seen.filter(e=>e.frame).at(-1);
 const screenshot=observedScreenshot||(cursor===0?events.find(e=>e.frame&&e.chapterIndex===current?.chapterIndex):undefined);
 const frameSrc=screenshot?.frame?'/evidence/replays/'+agent+'/'+screenshot.frame:null;
 const memoryEvent=seen.filter(e=>['store','recall','inject'].includes(e.kind)).at(-1);
 const memoryActive=current&&['store','recall','inject'].includes(current.kind)&&(playing||cursor!==0);
 function seek(n:number){setPlaying(false);setCursor(Math.min(total-1,Math.max(0,n)))}
 function choose(id:string){setAgent(id);const u=new URL(location.href);u.searchParams.set('agent',id);u.searchParams.set('environment','replay');history.replaceState(null,'',u.pathname+u.search)}
 function toggle(){if(ended)setCursor(0);setPlaying(p=>!p)}
 const Icon=current?kinds[current.kind].icon:Play;
 return <section ref={playerRef} role={present?'dialog':undefined} aria-modal={present||undefined} className={'rp-root '+(present?'rp-present':'')} aria-label="Recorded agent replay"><header className="rp-heading"><div><span className="rp-label">WATCH THE RUN</span><h1>{agent==='browser'?'From one run to the next.':'Watch the robot attempt.'}</h1><p>{agent==='browser'?'Real agent actions, captured screens, and the moment memory reaches the next agent.':'Camera observations, movement calls, and an independent arrival check.'}</p></div><button className="env-secondary" onClick={()=>setPresent(p=>!p)}>{present?<X size={15}/>:<Maximize2 size={15}/>} {present?'Exit presentation':'Present'}</button></header>
 <div className="rp-demo-select" role="group" aria-label="Replay agent">{demos.map(d=><button key={d.id} className={agent===d.id?'active':''} aria-pressed={agent===d.id} onClick={()=>choose(d.id)}><d.icon size={20}/><span><strong>{d.label}</strong><small>{d.description}</small></span><span className="rp-recorded">RECORDED</span></button>)}</div>
 {loading?<div className="rp-unavailable" role="status">Loading captured screens and trace…</div>:error||!recording||!current?<div className="rp-unavailable" role="alert"><h2>Replay unavailable</h2><p>{error||'No events found.'}</p><button className="env-secondary" onClick={()=>setRetry(n=>n+1)}>Retry</button></div>:<>
 <div className="rp-chapters">{recording.chapters.map((c,i)=><button key={c.id} className={current.chapterIndex===i?'active':''} onClick={()=>seek(events.findIndex(e=>e.chapter.id===c.id))}><span>0{i+1}</span>{c.title}{i<recording.chapters.length-1&&<ArrowRight size={15}/>}</button>)}<span>{recording.agent} · {recording.recordedAt.slice(0,10)}</span></div>
 <div className="rp-workspace"><div className="rp-visual"><div className="rp-windowbar"><span className="rp-window-dots">● ● ●</span><span>{agent==='browser'?'Agent browser':'Robot camera · MuJoCo office'}</span><span className="rp-recording-label"><i/>{playing?'REPLAYING':'RECORDED RUN'}</span></div><div className="rp-screen">
 {frameSrc&&imageError!==frameSrc?<img src={frameSrc} alt={screenshot?.frameCaption||'Actual captured agent observation'} onError={()=>setImageError(frameSrc)} className={'rp-frame '+(memoryActive?'dimmed':'')}/>:<div className="rp-frame-empty"><Globe2 size={34}/><strong>{frameSrc?'Captured image unavailable':'Before the first captured frame'}</strong><p>{frameSrc?'Trace events are still available.':'Start the replay to follow the recorded task.'}</p></div>}
 {memoryActive&&<div className="rp-memory-overlay"><div className="rp-memory-icon"><Icon size={26}/></div><span className="rp-label">MEMORABLE / {kinds[current.kind].label.toUpperCase()}</span><h2>{current.title}</h2><p>{current.summary}</p><pre>{JSON.stringify(current.output??current.input??{},null,2)}</pre><small>Recorded memory event · not live execution</small></div>}
 {!playing&&cursor===0&&<button className="rp-start-overlay" onClick={toggle}><span><Play size={27} fill="currentColor"/></span><strong>Play the actual run</strong><small>Step through recorded screens and tool calls</small></button>}
 </div><div className="rp-frame-caption"><Eye size={14}/><span>{screenshot&&!observedScreenshot?'Preview of the first captured screen':screenshot?.frameCaption||'No captured frame at this point'}{observedScreenshot&&observedScreenshot.id!==current.id?' · last available frame':''}</span></div>
 <div className={'rp-current '+(current.status==='failed'?'failed':'')} aria-live="polite"><Icon size={20}/><div><span>{current.phase==='before'?'Proposed action':kinds[current.kind].label} · {current.chapter.title}</span><h2>{current.title}</h2><p>{current.summary}</p></div>{current.status==='verified'?<Check size={19}/>:current.status==='failed'?<X size={19}/>:null}</div>
 </div><aside className="rp-trace"><div className="rp-trace-head"><span>EXECUTION TRACE</span><b>{String(cursor+1).padStart(2,'0')} / {String(total).padStart(2,'0')}</b></div><div className="rp-events">{events.map((e,i)=>{const EIcon=kinds[e.kind].icon;return <button ref={i===cursor?activeRow:undefined} key={e.id} className={(i===cursor?'current ':i<cursor?'seen ':'future ')+(e.status==='failed'?'failed':'')} onClick={()=>seek(i)} aria-current={i===cursor?'step':undefined}><span className="rp-event-icon">{e.status==='verified'?<Check size={13}/>:<EIcon size={13}/>}</span><div>{(i===0||events[i-1].chapterIndex!==e.chapterIndex)&&<small>{e.chapter.title}</small>}<strong>{e.tool||e.title}</strong><span>{e.tool?e.title:kinds[e.kind].label}{e.durationMs!==null?' · '+(e.durationMs/1000).toFixed(2)+'s recorded':''}</span></div><em>{String(i+1).padStart(2,'0')}</em></button>})}</div><div className="rp-memory-status"><Database size={15}/><div><span>MEMORY HANDOFF</span><p>{memoryEvent?memoryEvent.summary:'No memory event observed yet in this chapter.'}</p></div></div></aside></div>
 <div className="rp-controls"><button className="rp-play" onClick={toggle}>{playing?<Pause size={16} fill="currentColor"/>:ended?<RotateCcw size={16}/>:<Play size={16} fill="currentColor"/>}{playing?'Pause':ended?'Replay':'Play replay'}</button><button aria-label="Previous event" disabled={cursor===0} onClick={()=>seek(cursor-1)}><ChevronLeft size={20}/></button><input type="range" aria-label="Replay event" min={0} max={total-1} value={cursor} onChange={e=>seek(Number(e.target.value))}/><button aria-label="Next event" disabled={ended} onClick={()=>seek(cursor+1)}><ChevronRight size={20}/></button><label>Speed<select aria-label="Replay speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={0.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label><span>Step playback</span></div>
 <div className="rp-detail-grid"><section className="rp-inspector"><div className="rp-inspector-head"><span>{current.tool||kinds[current.kind].label}</span><span className={'rp-result '+current.status}>{current.phase==='before'?'Proposed action':current.status==='observed'?'Observed event':current.status==='failed'?(current.kind==='verify'?'Verification failed':'Failed event'):current.status==='verified'?'Verified':'Outcome unknown'}</span></div><div className="rp-payloads"><div><h3>{current.kind==='start'?'Task':'Input'}</h3><pre>{current.input!==undefined?JSON.stringify(current.input,null,2):current.kind==='start'?JSON.stringify({task:current.chapter.task},null,2):'No input captured for this event.'}</pre></div><div><h3>Recorded result</h3><pre>{current.output?JSON.stringify(current.output,null,2):'No structured result recorded for this event.'}</pre></div></div></section><section className="rp-provenance"><span className="rp-label">WHAT YOU ARE WATCHING</span><p>{recording.summary}</p><details><summary>Recording details and limits</summary><ul>{recording.limitations.map((l,i)=><li key={i}>{l}</li>)}</ul></details><div><a href={'/evidence/replays/'+agent+'/replay.json'} target="_blank" rel="noreferrer">Full trace <ExternalLink size={13}/></a><button onClick={()=>onMeasurements(agent)}>Other recorded measurements <ArrowUpRight size={13}/></button></div><small>Playback advances captured events at presentation speed. It does not execute tools or replay robot commands.</small></section></div>
 </>}
 </section>;
}
