import {z} from 'zod';
import {body,db,owner,failure} from '@/lib/server';
import {frameworks,roles} from '@/lib/connect/environment';
const dashboard=z.string().trim().max(1000).refine(v=>{if(!v)return true;try{const u=new URL(v);return !u.username&&!u.password&&!u.search&&!u.hash&&(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))}catch{return false}},'Use an HTTPS dashboard URL, or localhost HTTP, without credentials or query parameters.');
const schema=z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(80),framework:z.enum(frameworks),repo:z.string().trim().max(200).refine(v=>!v||/^(https:\/\/github\.com\/)?[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+\/?$/.test(v),'Use owner/repository or a GitHub repository URL.'),dashboardUrl:dashboard,intent:z.string().trim().max(1000),captureAt:z.enum(['task_complete','after_tool','explicit']),recallAt:z.enum(['before_task','before_tool','on_request']),metadata:z.array(z.object({key:z.string().trim().regex(/^[a-zA-Z][a-zA-Z0-9_.-]{0,79}$/),use:z.enum(roles)})).min(1).max(30),updatedAt:z.string().optional()}).refine(v=>new Set(v.metadata.map(f=>f.key)).size===v.metadata.length,'Metadata field names must be unique.').refine(v=>v.metadata.some(f=>f.use==='filter'),'Include at least one filter to define the workflow boundary.');
function sameOrigin(r:Request){const origin=r.headers.get('origin');if(origin&&origin!==new URL(r.url).origin)throw new Error('The request must come from this workspace.');}
export async function GET(){try{const user=await owner();const rows=await db().prepare('SELECT data FROM environments WHERE owner=? ORDER BY updated_at DESC').bind(user).all<{data:string}>();return Response.json({environments:rows.results.map(r=>JSON.parse(r.data))},{headers:{'cache-control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(r:Request){try{sameOrigin(r);const user=await owner();const parsed=schema.parse(await body(r));const at=new Date().toISOString();const environment={...parsed,createdAt:at,updatedAt:at};await db().prepare('INSERT INTO environments (id,owner,name,data,created_at,updated_at) VALUES (?,?,?,?,?,?)').bind(environment.id,user,environment.name,JSON.stringify(environment),at,at).run();return Response.json({environment},{status:201})}catch(e){return failure(e)}}
export async function PUT(r:Request){try{sameOrigin(r);const user=await owner();const parsed=schema.parse(await body(r));const old=await db().prepare('SELECT data FROM environments WHERE owner=? AND id=?').bind(user,parsed.id).first<{data:string}>();if(!old)throw new Error('Environment not found.');const existing=JSON.parse(old.data);if(parsed.updatedAt!==existing.updatedAt)throw new Error('This environment changed. Reload it before saving.');const at=new Date().toISOString();const environment={...parsed,createdAt:existing.createdAt,updatedAt:at};const result=await db().prepare('UPDATE environments SET name=?,data=?,updated_at=? WHERE owner=? AND id=? AND updated_at=?').bind(environment.name,JSON.stringify(environment),at,user,parsed.id,existing.updatedAt).run();if(result.meta.changes!==1)throw new Error('This environment changed. Reload it before saving.');return Response.json({environment})}catch(e){return failure(e)}}
